version: "3.8"

services:
  db:
    image: "mysql:8.0.28"
    environment:
      MYSQL_DATABASE: "super-app"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
  node-app:
    build: ./node
    ports:
      - "3000:3000"
  php-app:
    build: ./php
    ports:
      - "80:80"